# This patch requires a build of Xenia Canary that supports writable_code_segments, and having it enabled in the config.
# (Not merged as of 18-Dec-2022, see: https://github.com/xenia-canary/xenia-canary/pull/100)
# Commit 28f3eb6 or later of RB3Enhanced recommended, due to removing the DEMO check.

title_name = "Rock Band 3"
title_id = "45410914"
hash = [
	"464451C1022FFF32", # EA disc default.xex + TU5 applied
	"02B607A811A4C291"  # RB3DX modded pre-patched TU5 XEX
]

[[patch]]
	name = "Load RB3Enhanced.dll"
	author = "InvoxiPlayGames"
	is_enabled = true
	
	# Replaces a check in _start with a branch to LoadLibrary
	[[patch.be32]]
		address = 0x8283CD64
		value = 0x3C6082C6 # lis r3, 0x82C64350@hi
	[[patch.be32]]
		address = 0x8283CD68
		value = 0x60634350 # ori r3, r3, 0x82C64350@lo
	[[patch.be32]]
		address = 0x8283CD6C
		value = 0x48007F0D # bl LoadLibrary
	[[patch.string]]
		address = 0x82C64350
		value = "RB3Enhanced.dll"
